# DataFrame数据生成

In [12]:
import pandas as pd
import numpy as np
df = pd.DataFrame(data=None)
#data 可以是嵌套列表，字典，np二维数组等。。

In [13]:
#嵌套列表
df = pd.DataFrame([["贾巴尔","马龙","詹姆斯","科比","乔丹","诺维茨基","张伯伦","奥尼尔","摩西马龙","海耶斯"],[38387,36928,34030,33643,32292,31560,31419,28596,27409,27131]]).T
df.columns = ["姓名","得分"]
#df.index = [1,2,3,4,5,6,7,8,9,10]
df.index = range(1,11)
df

姓名     得分
1    贾巴尔  38387
2     马龙  36928
3    詹姆斯  34030
4     科比  33643
5     乔丹  32292
6   诺维茨基  31560
7    张伯伦  31419
8    奥尼尔  28596
9   摩西马龙  27409
10   海耶斯  27131

In [14]:
#字典
df2 = pd.DataFrame({"姓名":["贾巴尔","马龙","詹姆斯","科比","乔丹","诺维茨基","张伯伦","奥尼尔","摩西马龙","海耶斯"],"得分":[38387,36928,34030,33643,32292,31560,31419,28596,27409,27131]},index = range(1,11))
df2

姓名     得分
1    贾巴尔  38387
2     马龙  36928
3    詹姆斯  34030
4     科比  33643
5     乔丹  32292
6   诺维茨基  31560
7    张伯伦  31419
8    奥尼尔  28596
9   摩西马龙  27409
10   海耶斯  27131

In [15]:
#np 2维数组
data = np.array([("贾巴尔",38387),("马龙",36928),("詹姆斯",34030)])
df3 = pd.DataFrame(data, columns = ["姓名","得分"], index = range(1,4))
df3

姓名     得分
1  贾巴尔  38387
2   马龙  36928
3  詹姆斯  34030

# numpy 基本知识总结

## 1.np数组创建与访问

In [74]:
a = [1,2,3] #列表
b = [[1,2,3],[4,5,6]]#嵌套列表

#用列表创建np数组,np里面元素只能是同一个类型
x = np.array(a)#数学上叫向量
y = np.array(b)#数学上叫矩阵

In [75]:
print(x)
print(x.ndim)
print(x.shape)
print(x[0])#3行的1维数组
type(x)

[1 2 3]
1
(3,)
1


numpy.ndarray

In [76]:
print(y)

print(np.ndim(y))#判断y是几维数组
#print(y.ndim)

print(y.shape)#返回一个tuple，每一维有几个元素，比如y是一个2行3列的数组
print(y.shape[0])#第一维几个元素
print(y.shape[1])#第二维几个元素

print(y[0],y[1],sep = "\n")#下标访问元素，第一个下标是行下标
print(y[0][0],y[0][1],y[0][2])
print(y[1][0],y[1][1],y[1][2])

print(y.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
3
[1 2 3]
[4 5 6]
1 2 3
4 5 6
int32


In [77]:
#1.数据类型转换
y1 = y.astype(np.float32)
print(y1)
print(y1.dtype)

#2.创建np数组时就可以指定类型
y2 = np.array(b,dtype = np.float32)
print(y2)
print(y2.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float32
[[1. 2. 3.]
 [4. 5. 6.]]
float32


## 2.np数组计算

In [78]:
print(x)
print(y)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### 加减乘除

In [79]:
#加减乘除
print(y+x)
#print(np.add(y,x))

print(y-x)
#print(np.subtract(y,x))

print(y*x)
#print(np.multiply(y,x))

print(y/x)
#print(np.divide(y,x))

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


### **点积(dot .)**

                            数学公式
$$x = \begin{pmatrix} a_{1} & a_{2} & a_{3} \end{pmatrix}$$
$$y = \begin{pmatrix} b_{1} & b_{2} & b_{3} \end{pmatrix}$$
$$x \cdot y = a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3}$$

In [80]:
m = np.array([1,2,3])
n = np.array([4,5,6])

In [82]:
#2个向量的点积是个标量，是一个数值
print(m.dot(n))
print(n.dot(m))
print(np.dot(m,n))
print(np.dot(n,m))

32
32
32
32
